#!/usr/bin/perl -w

use BLClient;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "BLClient",
   ReceiveHandler => \&Receive);
$UNIVERSAL::blclient = BLClient->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::blclient->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::blclient->Execute();
